# Generated by Django 4.1.2 on 2022-11-02 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_remove_car_availability_car_car_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.customer')),
            ],
        ),
    ]
