# Generated by Django 4.1.2 on 2022-11-02 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(default='booked', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
