# Generated by Django 4.1.2 on 2022-11-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_booking_booking_date_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
