# Generated by Django 4.1.2 on 2022-11-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_date',
        ),
    ]
