# Generated by Django 4.1.2 on 2022-11-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_remove_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='car',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.IntegerField(),
        ),
    ]
