# Generated by Django 4.1.2 on 2022-11-02 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_alter_booking_car_alter_booking_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='order',
        ),
    ]
